language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: true

install:
  - travis_retry composer install --no-interaction --prefer-source
  - chmod -R 777 tests/temp
  - chmod -R 777 tests/views_temp